name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 8.x
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - run: dotnet build --configuration Release
      - name: Set prerelease version
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: (Get-Content dist/PSDODownloader.psd1) -replace "Prerelease =.+", "Prerelease = '$($env:GITHUB_SHA.Substring(0,7))'" | Set-Content dist/PSDODownloader.psd1
        
      - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - run: dotnet tool install --global AzureSignTool
        if: ${{ github.event_name != 'pull_request' }}
      - run: azuresigntool sign -kvu $env:KEY_VAULT_URL -kvc $env:KEY_VAULT_CERT -kvm -tr http://timestamp.acs.microsoft.com -td sha256 -fd sha256 dist/*.dll dist/*.psd1
        if: ${{ github.event_name != 'pull_request' }}
        env:
          KEY_VAULT_URL: ${{ vars.KEY_VAULT_URL }}
          KEY_VAULT_CERT: ${{ vars.KEY_VAULT_CERT }}

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: natescherer/publish-powershell-action@0ca93e133f1cf68a79cbc94287dc31887534b401 # v1.1.1
        with:
          token: ${{ secrets.PS_GALLERY_KEY }}
          target: gallery
          path: dist
      - uses: natescherer/publish-powershell-action@0ca93e133f1cf68a79cbc94287dc31887534b401 # v1.1.1
        with:
          token: ${{ github.token }}
          target: packages
          path: dist

  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ github.token }}
          release-type: simple
